# H2 Connection
# http://localhost:8080/h2-console
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

# H2 Client
  h2:
    console:
      enabled: true
      path: /h2-console

# Show SQL
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: none

      # Export sql script generate by hibernate
      #jakarta:
      #  persistence:
      #    schema-generation:
      #      create-source: metadata
      #      scripts:
      #        action: create
      #        create-target: schema.sql
      #  hbm2ddl:
      #    delimiter: ;



logging:
  level:
    root: DEBUG