create table book_author (
        id_author bigint not null,
        id_book bigint not null,
        primary key (id_author, id_book)
    );

    create table book_category (
        id_book bigint not null,
        id_category bigint not null,
        primary key (id_book, id_category)
    );

    create table tb_author (
        id bigint generated by default as identity,
        about TEXT,
        name varchar(255),
        primary key (id)
    );

    create table tb_book (
        book_year integer,
        pages integer,
        id bigint generated by default as identity,
        image varchar(255),
        language varchar(255),
        title varchar(255),
        primary key (id)
    );

    create table tb_category (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    alter table if exists book_author
       add constraint FKn7ab8d8s898lvt2xva3thcsm1
       foreign key (id_author)
       references tb_author;

    alter table if exists book_author
       add constraint FKcb67lvys36pra8fh53tfd2rsh
       foreign key (id_book)
       references tb_book;

    alter table if exists book_category
       add constraint FKhawemhdxco4lsbq4b5hlrga6r
       foreign key (id_book)
       references tb_book;

    alter table if exists book_category
       add constraint FKbcfw8xxc7mht2yh7w50iwt3jv
       foreign key (id_category)
       references tb_category;